
cluster_shield:
  log_level: debug
  cluster_config:
    name: ${cluster_name}
  features:
    admission_control:
      enabled: true
      deny_on_error: true
      dry_run: false
      container_vulnerability_management:
        enabled: true
    audit:
      enabled: true
    container_vulnerability_management:
      enabled: true
    posture:
      enabled: true
  sysdig_endpoint:
    api_url: ${url}
    secure_api_token: ${secure_api_token}
    access_key: ${access_key}
image:
  tag: 466cae8
  repository: us-docker.pkg.dev/sysdig-artifact-registry-dev/gar-docker/agent/cluster-shield
replicaCount: 1
imagePullSecrets:
  - name: ${gar_secret_name}