global:
  clusterConfig:
    name: ${cluster_name}
  sysdig:
    region: us4
    accessKey: ${access_key}
    secureAPIToken: ${secure_api_token}
  kspm:
    deploy: true
  loggingLevel: "DEBUG"
## rapid response enablement
rapidResponse:
  enabled: false
  rapidResponse:
    passphrase: YWJj  
nodeAnalyzer:
  enabled: true
  nodeAnalyzer:
    benchmarkRunner:
      deploy: false
    hostAnalyzer:
      deploy: false
    runtimeScanner:
      deploy: false      
      ## eveConnector is used for third party integrations
      eveConnector:
        deploy: false
      settings:
        eveEnabled: true
      env: ## set env variables for runtimeScanner
        SCANNER_RUN_TIMEOUT: 3h
      image: ## set image for runtimeScanner
        repository: sysdig/vuln-runtime-scanner
  secure:
    vulnerabilityManagement:
      newEngineOnly: true
agent:
  image:
    tag: 13.0.4 ## set agent version
  ebpf:
    enabled: true
    kind: universal_ebpf

clusterScanner:
  enabled: false
  eveEnabled: true
  sslVerifyCertificate: true
  # scannerMode: "multi"
  scannerMode: "local"
  replicaCount: 2

  runtimeStatusIntegrator:
    # multiCluster:
      # kubeconfigSecretName: "sysdig-cluster-scanner-clusters-conf"
    image:
      registry: "quay.io"
      repository: "sysdig/runtime-status-integrator"
    resources:
      limits:
        cpu: "1"
        memory: 350Mi
      requests:
        cpu: "350m"
        memory: 350Mi
  imageSbomExtractor:
    image:
      registry: "quay.io"
      repository: "sysdig/image-sbom-extractor"
    resources:
      limits:
        cpu: "1"
        memory: 350Mi
      requests:
        cpu: "350m"
        memory: 350Mi

