global:
  clusterConfig:
    name: ${cluster_name}
  sysdig:
    region: ${region}
    accessKey: ${access_key}
    secureAPIToken: ${secure_api_token}
  # proxy:
  #   httpProxy:  myhttpproxy
  #   httpsProxy: myhttpsproxy
  #   noProxy: noproxylist1,noproxylist2
  kspm:
    deploy: true
nodeAnalyzer:
## disable nodeAnalyzer completely as I'm using host-shield and cluster-shield
  enabled: false
  nodeAnalyzer:
    benchmarkRunner:
      deploy: false
    hostAnalyzer:
      deploy: false
    runtimeScanner:
      deploy: false
  secure:
    vulnerabilityManagement:
      newEngineOnly: true
kspmCollector:
  enabled: false
agent:
## requires agent above 13.3.0
## drop all capabilities and add a static list present of agent helpers.tpl
  privileged: false
## extra volumes section is required for host-shield
  extraVolumes:
    volumes:
    - name: root-vol
      hostPath:
        path: /
    - name: tmp-vol
      hostPath:
        path: /tmp
    mounts:
    - mountPath: /host
      name: root-vol
      readOnly: true
    # The host's tmp directory needs to be writeable for kspm-analyzer to create the scripts it runs.
    - mountPath: /host/tmp
      name: tmp-vol
  # image:
    # tag: 13.2.0
  prometheus:
    file: true
    yaml: 
      global:
        scrape_interval: 10s
      scrape_configs:
      - job_name: 'k8s-pods'
        sample_limit: 40000
        tls_config:
          insecure_skip_verify: true
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
          # Only scrape running pods to workaround issue where non-running pods still exist with a scrape loop
        - action: drop
          source_labels: [__meta_kubernetes_namespace]
          regex: monitoring
  ebpf:
    enabled: true
    kind: universal_ebpf
  sysdig:
    settings:
      feature:
        mode: monitor
      prometheus_exporter:
        enabled: true
        export_health_metrics: true
      sysdig_api_endpoint: ${sysdig_secure_url}
      host_scanner:
        enabled: true
        host_fs_mount_path: /host
        scan_on_start: true
      kspm_analyzer:
        enabled: true
  daemonset:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9544"
  tolerations:
  - key: MyTolerationKey
    operator: Equal
    value: MyTolerationValue
    effect: NoSchedule
admissionController:
  enabled: false
clusterShield:
  tolerations:
  - key: MyTolerationKey
    operator: Equal
    value: MyTolerationValue
    effect: NoSchedule
  podAnnotations: 
    prometheus.io/scrape: "true"
  enabled: true
  cluster_shield:
    log_level: debug
    features:
      admission_control:
        dry_run: false
        deny_on_error: false
        enabled: true
        container_vulnerability_management:
          enabled: true
      audit:
        enabled: true
      container_vulnerability_management:
        enabled: true
        local_cluster:
          enabled: true
          registry_secrets: 
            - namespace: sysdig-agent
              secrets:
                - gar-cred
      posture:
        enabled: true
  image:
    # tag: 466cae8
    # repository: us-docker.pkg.dev/sysdig-artifact-registry-dev/gar-docker/agent/cluster-shield
  replicaCount: 1
  imagePullSecrets: 
    - name: "gar-cred"