global:
  clusterConfig:
    name: ${cluster_name}
  sysdig:
    region: ${region}
    accessKey: ${access_key}
    secureAPIToken: ${secure_api_token}
  # proxy:
  #   httpProxy:  myhttpproxy
  #   httpsProxy: myhttpsproxy
  #   noProxy: noproxylist1,noproxylist2
  kspm:
    deploy: true
nodeAnalyzer:
  enabled: true
  nodeAnalyzer:
    benchmarkRunner:
      deploy: false
    hostAnalyzer:
      deploy: false
    runtimeScanner:
      deploy: false
  secure:
    vulnerabilityManagement:
      newEngineOnly: true
kspmCollector:
  enabled: false
agent:
  image:
    tag: 13.2.0
  ebpf:
    enabled: true
    kind: universal_ebpf
  tolerations:
  - key: MyTolerationKey
    operator: Equal
    value: MyTolerationValue
    effect: NoSchedule
admissionController:
  enabled: false
clusterShield:
  tolerations:
  - key: MyTolerationKey
    operator: Equal
    value: MyTolerationValue
    effect: NoSchedule
  podAnnotations: 
    prometheus.io/scrape: "true"
  enabled: true
  cluster_shield:
    log_level: debug
    features:
      admission_control:
        dry_run: false
        deny_on_error: true
        enabled: true
        container_vulnerability_management:
          enabled: true
      audit:
        enabled: true
      container_vulnerability_management:
        enabled: true
        local_cluster:
          enabled: true
          registry_secrets: 
            - namespace: sysdig-agent
              secrets:
                - gar-cred
      posture:
        enabled: true
  image:
    # tag: 466cae8
    # repository: us-docker.pkg.dev/sysdig-artifact-registry-dev/gar-docker/agent/cluster-shield
  replicaCount: 1
  imagePullSecrets: 
    - name: "gar-cred"